global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'mvarunmathi2004@gmail.com'
  smtp_auth_username: 'mvarunmathi2004@gmail.com'
  smtp_auth_password: 'ahiw jlsz dzxa ohso'
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alert'
  routes:
    - receiver: 'slack-notifications'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'varunm.22it@kongu.edu'
        send_resolved: true
        headers:
          subject: 'Test Alert Notification'

  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#new-channel'
        username: 'alertmanager'
        icon_emoji: ':warning:'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'